apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bookstack
  labels:
    service: heimdall-claim0
  name: heimdall-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
