apiVersion: v1
kind: Service
metadata:
  namespace: bookstack
  labels:
    service: mariadb
  name: bookstackdb
spec:
  type: ClusterIP
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    service: mariadb
