apiVersion: v1
kind: Service
metadata:
  namespace: bookstack
  labels:
    service: nginx
  name: nginx
spec:
  type: LoadBalancer
  ports:
    - name: "81"
      port: 81
      targetPort: 80
    - name: "444"
      port: 444
      targetPort: 443
  selector:
    service: nginx
