apiVersion: v1
kind: Service
metadata:
  namespace: bookstack
  labels:
    service: bookstack
  name: bookstack
spec:
  type: LoadBalancer
  ports:
    - name: "6875"
      port: 6875
      targetPort: 80
  selector:
    service: bookstack
