apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bookstack
  labels:
    service: mariadb-claim0
  name: mariadb-claim0
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
